apiVersion: v1
kind: Secret
metadata:
  name: reactdemo-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONOGO_URI: {{ .Values.secrets.mongoURI }}
  JWT_SECRET: {{ .Values.secrets.jwtSecrets}}